import type {
  Category,
  FAQ,
  GalleryImage,
  MenuItem,
  OpeningHour,
  Promotion,
  RestaurantLocation,
  RestaurantSettings,
  Review,
} from '@/types/restaurant'

// La primera sucursal marcada con isPrimary recibe consultas generales y pedidos por defecto.
export const locations: RestaurantLocation[] = [
  {
    id: 'libertad',
    name: 'Av. Libertad',
    address: 'Av. Libertad, Villa Carlos Paz',
    whatsapp: '5493541574028',
    coordinates: { lat: -31.41987952849029, lng: -64.49131158026547 },
    isPrimary: true,
  },
  {
    id: 'uruguay',
    name: 'Uruguay 579',
    address: 'Uruguay 579, Villa Carlos Paz',
    whatsapp: '5493541331653',
    coordinates: { lat: -31.416293983642454, lng: -64.4928864188588 },
  },
]

export const restaurantSettings: RestaurantSettings = {
  name: 'Ranch VCP',
  tagline: 'Lomos con fama · Pizzas excelentes · WhatsApp directo',
  description:
    'Los mejores lomos, pizzas y hamburguesas en Villa Carlos Paz.',
  whatsapp: '5493541574028',
  address: 'Av. Libertad · Uruguay 579',
  neighborhood: 'Córdoba, Argentina',
  instagram: 'ranch.vcp',
  googleMapsUrl: 'https://maps.google.com/?q=Ranch+VCP+Villa+Carlos+Paz+C%C3%B3rdoba',
  heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80',
  isOpen: true,
}

export const categories: Category[] = [
  {
    id: 'burgers',
    name: 'Burgers',
    description: 'Medallones, panes brioche y papas que salen fuerte.',
    icon: 'burger',
    order: 1,
    isActive: true,
  },
  {
    id: 'pizzas',
    name: 'Pizzas',
    description: 'Masa aireada, horno bien arriba y cortes para compartir.',
    icon: 'pizza',
    order: 2,
    isActive: true,
  },
  {
    id: 'lomos',
    name: 'Lomos',
    description: 'Clásicos de noche cordobesa con pan tostado y buen volumen.',
    icon: 'lomo',
    order: 3,
    isActive: true,
  },
  {
    id: 'empanadas',
    name: 'Empanadas',
    description: 'Horno rápido para abrir o acompañar la mesa.',
    icon: 'empanadas',
    order: 4,
    isActive: true,
  },
  {
    id: 'picadas',
    name: 'Picadas y papas',
    description: 'Tablas, provoletas y papas para pedir en grupo.',
    icon: 'picada',
    order: 5,
    isActive: true,
  },
  {
    id: 'bebidas',
    name: 'Bebidas',
    description: 'Tragos, vermut y opciones frescas para acompañar.',
    icon: 'bebidas',
    order: 6,
    isActive: true,
  },
]

export const menuItems: MenuItem[] = [
  {
    id: '1',
    categoryId: 'burgers',
    name: 'Ranch Classic',
    description: 'Doble medallon, cheddar, cebolla grillada, pepinos y salsa Ranch con papas finas.',
    price: 16900,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    ingredients: [
      { id: 'medallon-vacuno', name: 'Doble medallon vacuno' },
      { id: 'cheddar', name: 'Cheddar' },
      { id: 'cebolla-grillada', name: 'Cebolla grillada' },
      { id: 'pepinos', name: 'Pepinos' },
      { id: 'salsa-ranch', name: 'Salsa Ranch' },
    ],
    tags: ['Recomendado'],
    isAvailable: true,
    isFeatured: true,
    order: 1,
  },
  {
    id: '2',
    categoryId: 'burgers',
    name: 'Doble cheddar y panceta',
    description: 'Dos medallones smash, cheddar fundido, panceta crocante y mayo ahumada.',
    price: 18200,
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80',
    ingredients: [
      { id: 'smash-burger', name: 'Medallones smash' },
      { id: 'cheddar-extra', name: 'Cheddar fundido' },
      { id: 'panceta', name: 'Panceta crocante' },
      { id: 'mayo-ahumada', name: 'Mayo ahumada' },
    ],
    tags: ['Mas pedido'],
    isAvailable: true,
    isFeatured: false,
    order: 2,
  },
  {
    id: '3',
    categoryId: 'burgers',
    name: 'Crispy chicken',
    description: 'Pollo crocante, coleslaw fresco, pepinos y salsa de mostaza dulce.',
    price: 16100,
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80',
    ingredients: [
      { id: 'pollo-crocante', name: 'Pollo crocante' },
      { id: 'coleslaw', name: 'Coleslaw' },
      { id: 'pepinos-pollo', name: 'Pepinos' },
      { id: 'mostaza-dulce', name: 'Salsa de mostaza dulce' },
    ],
    tags: [],
    isAvailable: true,
    isFeatured: false,
    order: 3,
  },
  {
    id: '4',
    categoryId: 'pizzas',
    name: 'Fugazzeta Ranch',
    description: 'Mozzarella, cebolla blanca, provolone rallado y toque de oregano.',
    price: 18900,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    ingredients: [
      { id: 'masa-pizza', name: 'Masa de pizza' },
      { id: 'mozzarella-pizza', name: 'Mozzarella' },
      { id: 'cebolla-blanca', name: 'Cebolla blanca' },
      { id: 'provolone-rallado', name: 'Provolone rallado' },
    ],
    tags: ['Recomendado', 'Vegetariano'],
    isAvailable: true,
    isFeatured: true,
    order: 1,
  },
  {
    id: '5',
    categoryId: 'pizzas',
    name: 'Pepperoni hot honey',
    description: 'Pepperoni, mozzarella y un final apenas picante con miel especiada.',
    price: 20100,
    imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&q=80',
    ingredients: [
      { id: 'pepperoni', name: 'Pepperoni' },
      { id: 'mozzarella-hot', name: 'Mozzarella' },
      { id: 'miel-picante', name: 'Miel especiada' },
    ],
    tags: ['Nuevo'],
    isAvailable: true,
    isFeatured: false,
    order: 2,
  },
  {
    id: '6',
    categoryId: 'pizzas',
    name: 'Cuatro quesos',
    description: 'Mozzarella, azul, parmesano y provolone sobre salsa suave.',
    price: 19600,
    imageUrl: 'https://images.unsplash.com/photo-1548365328-9f547fb0953b?w=600&q=80',
    ingredients: [
      { id: 'queso-mozzarella', name: 'Mozzarella' },
      { id: 'queso-azul', name: 'Queso azul' },
      { id: 'parmesano-pizza', name: 'Parmesano' },
      { id: 'provolone-pizza', name: 'Provolone' },
    ],
    tags: ['Vegetariano'],
    isAvailable: false,
    isFeatured: false,
    order: 3,
  },
  {
    id: '7',
    categoryId: 'lomos',
    name: 'Lomo completo',
    description: 'Lomo tierno, jamon, queso, lechuga, tomate, huevo y mayo casera con papas.',
    price: 19400,
    imageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80',
    ingredients: [
      { id: 'lomo-vacuno', name: 'Lomo vacuno' },
      { id: 'jamon-cocido', name: 'Jamon cocido' },
      { id: 'queso-barra', name: 'Queso en barra' },
      { id: 'lechuga', name: 'Lechuga' },
      { id: 'tomate', name: 'Tomate' },
      { id: 'huevo', name: 'Huevo' },
    ],
    tags: ['Mas pedido'],
    isAvailable: true,
    isFeatured: true,
    order: 1,
  },
  {
    id: '8',
    categoryId: 'lomos',
    name: 'Lomo cheddar crispy',
    description: 'Lomo, cheddar, cebolla crispy y alioli tostado en pan suave.',
    price: 20100,
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=600&q=80',
    ingredients: [
      { id: 'lomo-cheddar', name: 'Lomo vacuno' },
      { id: 'cheddar-lomo', name: 'Cheddar' },
      { id: 'cebolla-crispy', name: 'Cebolla crispy' },
      { id: 'alioli', name: 'Alioli tostado' },
    ],
    tags: ['Recomendado'],
    isAvailable: true,
    isFeatured: false,
    order: 2,
  },
  {
    id: '9',
    categoryId: 'lomos',
    name: 'Lomo veggie grill',
    description: 'Pan de papa, provoleta, portobellos, cebolla y morrones asados.',
    price: 17600,
    imageUrl: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=600&q=80',
    ingredients: [
      { id: 'pan-papa', name: 'Pan de papa' },
      { id: 'provoleta-lomo', name: 'Provoleta' },
      { id: 'portobellos', name: 'Portobellos' },
      { id: 'morrones-asados', name: 'Morrones asados' },
    ],
    tags: ['Vegetariano'],
    isAvailable: false,
    isFeatured: false,
    order: 3,
  },
  {
    id: '10',
    categoryId: 'empanadas',
    name: 'Empanadas de carne cortada a cuchillo',
    description: 'Tres unidades con relleno jugoso, cebolla y especias suaves.',
    price: 7600,
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&q=80',
    ingredients: [
      { id: 'carne-cuchillo', name: 'Carne cortada a cuchillo' },
      { id: 'cebolla-empanada', name: 'Cebolla' },
      { id: 'comino', name: 'Comino suave' },
    ],
    tags: ['Mas pedido'],
    isAvailable: true,
    isFeatured: false,
    order: 1,
  },
  {
    id: '11',
    categoryId: 'empanadas',
    name: 'Empanadas de jamon y queso',
    description: 'Tres unidades con mozzarella hilada y jamon cocido.',
    price: 7200,
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&q=80',
    ingredients: [
      { id: 'jamon-empanada', name: 'Jamon cocido' },
      { id: 'mozzarella-empanada', name: 'Mozzarella' },
    ],
    tags: [],
    isAvailable: true,
    isFeatured: false,
    order: 2,
  },
  {
    id: '12',
    categoryId: 'empanadas',
    name: 'Empanadas de humita',
    description: 'Tres unidades cremosas con choclo, bechamel liviana y queso.',
    price: 7200,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80',
    ingredients: [
      { id: 'choclo', name: 'Choclo' },
      { id: 'bechamel', name: 'Bechamel liviana' },
      { id: 'queso-humita', name: 'Queso' },
    ],
    tags: ['Vegetariano'],
    isAvailable: true,
    isFeatured: false,
    order: 3,
  },
  {
    id: '13',
    categoryId: 'picadas',
    name: 'Papas Ranch cheddar',
    description: 'Papas crujientes con cheddar fundido, verdeo y panceta crocante.',
    price: 12800,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=600&q=80',
    ingredients: [
      { id: 'papas-crujientes', name: 'Papas crujientes' },
      { id: 'cheddar-papas', name: 'Cheddar fundido' },
      { id: 'verdeo', name: 'Verdeo' },
      { id: 'panceta-papas', name: 'Panceta crocante' },
    ],
    tags: ['Mas pedido'],
    isAvailable: true,
    isFeatured: false,
    order: 1,
  },
  {
    id: '14',
    categoryId: 'picadas',
    name: 'Picada de la casa',
    description: 'Fiambres, quesos, aceitunas, escabeches y pan caliente para compartir.',
    price: 24600,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    ingredients: [
      { id: 'fiambres', name: 'Fiambres seleccionados' },
      { id: 'quesos', name: 'Quesos' },
      { id: 'aceitunas', name: 'Aceitunas' },
      { id: 'escabeches', name: 'Escabeches' },
    ],
    tags: ['Recomendado'],
    isAvailable: true,
    isFeatured: true,
    order: 2,
  },
  {
    id: '15',
    categoryId: 'picadas',
    name: 'Provoleta al hierro',
    description: 'Provoleta dorada con tomate concasse, oregano y oliva.',
    price: 9800,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-6c1c8b1f4323?w=600&q=80',
    ingredients: [
      { id: 'provoleta', name: 'Provoleta' },
      { id: 'tomate-concasse', name: 'Tomate concasse' },
      { id: 'oregano-provoleta', name: 'Oregano' },
    ],
    tags: ['Vegetariano'],
    isAvailable: true,
    isFeatured: false,
    order: 3,
  },
  {
    id: '16',
    categoryId: 'bebidas',
    name: 'Limonada ginger mint',
    description: 'Limonada fresca con menta, jengibre y apenas soda.',
    price: 5200,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80',
    ingredients: [
      { id: 'limon-bebida', name: 'Limon' },
      { id: 'menta-bebida', name: 'Menta' },
      { id: 'jengibre-bebida', name: 'Jengibre' },
    ],
    tags: ['Sin TACC'],
    isAvailable: true,
    isFeatured: false,
    order: 1,
  },
  {
    id: '17',
    categoryId: 'bebidas',
    name: 'Vermut Ranch',
    description: 'Vermut artesanal, naranja fresca, soda y aceituna verde.',
    price: 6900,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80',
    ingredients: [
      { id: 'vermut', name: 'Vermut artesanal' },
      { id: 'naranja-vermut', name: 'Naranja' },
      { id: 'soda-vermut', name: 'Soda' },
    ],
    tags: ['Recomendado'],
    isAvailable: true,
    isFeatured: false,
    order: 2,
  },
  {
    id: '18',
    categoryId: 'bebidas',
    name: 'Copa de Malbec',
    description: 'Malbec mendocino de trago amable para burger, pizza o tabla.',
    price: 7600,
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80',
    ingredients: [{ id: 'malbec', name: 'Malbec mendocino' }],
    tags: [],
    isAvailable: true,
    isFeatured: false,
    order: 3,
  },
]

export const promotions: Promotion[] = [
  {
    id: '1',
    title: 'Combo noche Ranch',
    description: 'Burger o pizza individual con papas y bebida para resolver rapido.',
    price: 21900,
    originalPrice: 24600,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    isActive: true,
  },
]

export const openingHours: OpeningHour[] = [
  { day: 'Lunes', openTime: '', closeTime: '', isClosed: true },
  { day: 'Martes', openTime: '12:30', closeTime: '15:30', isClosed: false },
  { day: 'Martes noche', openTime: '20:00', closeTime: '00:00', isClosed: false },
  { day: 'Miercoles', openTime: '12:30', closeTime: '15:30', isClosed: false },
  { day: 'Miercoles noche', openTime: '20:00', closeTime: '00:00', isClosed: false },
  { day: 'Jueves', openTime: '12:30', closeTime: '15:30', isClosed: false },
  { day: 'Jueves noche', openTime: '20:00', closeTime: '00:30', isClosed: false },
  { day: 'Viernes', openTime: '12:30', closeTime: '16:00', isClosed: false },
  { day: 'Viernes noche', openTime: '20:00', closeTime: '01:30', isClosed: false },
  { day: 'Sabado', openTime: '12:30', closeTime: '16:00', isClosed: false },
  { day: 'Sabado noche', openTime: '20:00', closeTime: '01:30', isClosed: false },
  { day: 'Domingo', openTime: '20:00', closeTime: '00:00', notes: 'Solo noche', isClosed: false },
]

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'La reserva queda confirmada automaticamente?',
    answer: 'No. Mandas la consulta por WhatsApp y el equipo del local te confirma segun disponibilidad.',
  },
  {
    id: '2',
    question: 'La carta que veo esta actualizada?',
    answer: 'Si. Platos, precios y disponibilidad se revisan antes de cada servicio para que no mires humo.',
  },
  {
    id: '3',
    question: 'Hay opciones vegetarianas?',
    answer: 'Si. Estan marcadas dentro de burgers, pizzas, empanadas y picadas para que entren rapido en el recorrido.',
  },
  {
    id: '4',
    question: 'Se puede pedir para retirar?',
    answer: 'Si. Podes revisar la carta, escribir al local y coordinar retiro o reserva desde el mismo canal.',
  },
  {
    id: '5',
    question: 'Aceptan grupos grandes?',
    answer: 'Si. Para mesas grandes conviene escribir con tiempo para que el local organice lugar y horario.',
  },
  {
    id: '6',
    question: 'Donde esta Ranch VCP?',
    answer: 'En Villa Carlos Paz, Cordoba. El enlace a mapa queda visible en la web para abrirlo sin salir a buscar.',
  },
]

export const galleryImages: GalleryImage[] = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1400&q=80',
    alt: 'Salon nocturno de Ranch VCP',
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1400&q=80',
    alt: 'Mesa servida lista para compartir',
  },
  {
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1400&q=80',
    alt: 'Burger de la casa con papas',
  },
  {
    id: '4',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1400&q=80',
    alt: 'Pizza recien salida del horno',
  },
  {
    id: '5',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1400&q=80',
    alt: 'Barra con cocteles cortos y vermut',
  },
  {
    id: '6',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1400&q=80',
    alt: 'Cocina de despacho en servicio',
  },
]

// Placeholder de reseñas hasta cargar las reales de Google/Instagram del local.
export const reviews: Review[] = [
  {
    id: '1',
    name: 'Caro M.',
    text: 'La Ranch Classic es de otro planeta. Pedimos por WhatsApp y estaba todo listo cuando llegamos.',
    rating: 5,
    context: 'Cena de viernes',
  },
  {
    id: '2',
    name: 'Julián P.',
    text: 'Fuimos en grupo un sábado a la noche, mesa lista y la picada salió volando. Volvemos seguro.',
    rating: 5,
    context: 'Mesa grande',
  },
  {
    id: '3',
    name: 'Sofi R.',
    text: 'La fugazzeta y el vermut, combo perfecto. El lugar de noche tiene un clima buenísimo.',
    rating: 5,
    context: 'Salida de a dos',
  },
  {
    id: '4',
    name: 'Marcos D.',
    text: 'Pedimos delivery con la carta del QR y llegó rapidísimo. Los lomos son enormes, para compartir.',
    rating: 4,
    context: 'Delivery',
  },
  {
    id: '5',
    name: 'Agus T.',
    text: 'Reservé por WhatsApp en dos mensajes. Atención cercana y las papas con cheddar, imperdibles.',
    rating: 5,
    context: 'Reserva directa',
  },
  {
    id: '6',
    name: 'Euge L.',
    text: 'De paso por Carlos Paz caímos sin reserva y nos acomodaron igual. La burger de la casa, top.',
    rating: 5,
    context: 'Turistas',
  },
]
